CREATE TABLE don (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    amount DOUBLE NOT NULL,
    payment_method VARCHAR(100) NOT NULL,
    reference VARCHAR(255) NOT NULL,
    don_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);